In [1]:
1+2

3

In [2]:
7/5

1.4

In [3]:
7//5

1

In [4]:
3**2

9

In [5]:
type(10)

int

In [6]:
type(2.718)

float

In [7]:
type("hello")

str

In [8]:
type('hello')

str

In [9]:
x = 10
print(x)
type(x)

10


int

In [10]:
y = 3.14
print(x*y)
type(x*y)

31.400000000000002


float

In [11]:
# p.30 list
a = [1,2,3,4,5]
print(a)

[1, 2, 3, 4, 5]


In [12]:
a[0]

1

In [13]:
a[4]

5

In [14]:
a[4] = 99
print(a)

[1, 2, 3, 4, 99]


In [15]:
print(a[0:2])

[1, 2]


In [16]:
a[1:]

[2, 3, 4, 99]

In [17]:
a[:3]

[1, 2, 3]

In [18]:
a[:-1]

[1, 2, 3, 4]

In [19]:
a[:-2]

[1, 2, 3]

In [20]:
# p.31 dictionary
me = {'height':180}
me['height']

180

In [21]:
me['weight'] = 70
print(me)

{'height': 180, 'weight': 70}


In [22]:
# bool
hungry = False
sleepy = True
type(hungry)

bool

In [23]:
not hungry

True

In [24]:
hungry and sleepy

False

In [25]:
hungry or sleepy

True

In [26]:
# p.32 if statement
if not hungry:
    print("I am not hungry.")

I am not hungry.


In [27]:
if sleepy:
    print("I am sleepy.")
    if hungry:
        print("I am hungry.")
    else:
        print("I am not hungry.")
else:
    print("I am not sleepy.")
    if hungry:
        print("I am hungry.")
    else:
        print("I am not hungry.")


I am sleepy.
I am not hungry.


In [28]:
# p.33 for statement
for i in [2,4,8]:
    print(i)

2
4
8


In [29]:
# function
def hello():
    print("Hello, world!")

In [30]:
hello()

Hello, world!


In [31]:
def hello(object):
    print("Hello, "+ object + "!")

In [32]:
hello("cat")

Hello, cat!


In [33]:
class Man:
    """Sample class"""
    def __init__(self, name):
        self.name = name
        print("Initilized!")

    def hello(self):
        print("Hello " + self.name + "!")

    def goodbye(self):
        print("Good-bye " + self.name + "!")

In [34]:
m = Man("David")

Initilized!


In [35]:
m = Man("David")
m.hello()

Initilized!
Hello David!


In [36]:
m.goodbye()

Good-bye David!


# Numpy

NumPy is the fundamental package for scientific computing with Python:

  1) a powerful N-dimensional array object

  2) sophisticated (broadcasting) functions

  3) tools for integrating C/C++ and Fortran code

  4) useful linear algebra, Fourier transform, and random number capabilities

In [37]:
a = [7, 8, 9]
print(a)

[7, 8, 9]


In [38]:
type(a)

list

In [39]:
import numpy as np
x = np.array([1, 2, 3]) # integer elements
print(x)

[1 2 3]


In [40]:
import numpy
x = numpy.array([1, 2, 3]) # integer elements
print(x)

[1 2 3]


In [41]:
# Numpy array, p.36
import numpy as np
x = np.array([1.0, 2.0, 3.0])
print(x)

[1. 2. 3.]


In [42]:
type(x)

numpy.ndarray

In [43]:
x.shape

(3,)

In [44]:
a = np.array([[1, 2, 3], [4, 5, 6]])
print(a)

[[1 2 3]
 [4 5 6]]


In [45]:
type(a)

numpy.ndarray

In [46]:
a.shape

(2, 3)

In [47]:
np.size(a)

6

In [48]:
np.size(x)

3

In [49]:
# Numpy arithmetic operation :
x = np.array([1.0, 2.0, 3.0])
y = np.array([2.0, 4.0, 6.0])
x + y

array([3., 6., 9.])

In [50]:
x - y

array([-1., -2., -3.])

In [51]:
x * y     # element-by-element multiplication

array([ 2.,  8., 18.])

In [52]:
np.dot(x, y)

28.0

In [53]:
np.inner(x, y)

28.0

In [54]:
x / y     # element-by-element division

array([0.5, 0.5, 0.5])

In [55]:
x / 2.0   # broadcast

array([0.5, 1. , 1.5])

In [56]:
x / 2     # broadcast

array([0.5, 1. , 1.5])

In [57]:
# Numpy N-dimensional array
A = np.array([1, 2], [3, 4])
print(A)

TypeError: Field elements must be 2- or 3-tuples, got '3'

In [ ]:
# Numpy N-dimensional array
A = np.array([[1, 2], [3, 4]])
print(A)

In [ ]:
A.shape

In [ ]:
A.dtype

In [ ]:
np.size(A)

In [ ]:
B = np.array([[3, 0], [0, 6]])
A + B

In [ ]:
print(A)
print(B)

In [ ]:
A * B    # element-by-element matrix multiplication

In [ ]:
A * 10   # broadcast

In [ ]:
A = np.array([[1, 2], [3, 4]])
B = np.array([10, 20])
A * B

Accessing the elements

In [ ]:
import numpy as np
X = np.array([[51, 55], [14, 19], [0, 4]])
print(X)

In [ ]:
X[0]

In [ ]:
X[0][1]

In [ ]:
for row in X:
    print(row)

In [ ]:
X = X.flatten()  # X를 1차원 배열로 변환 (평탄화)
print(X)

In [ ]:
 X > 15

In [ ]:
Y = X[X > 15]
print(Y)

인덱스를 array (배열)로 지정해 한 번에
 여러 원소에 접근할 수도 있음.

In [ ]:
X[np.array([0, 2, 4])]

Numpy is the core library for scientific computing in Python. It provides a high-performance multidimensional array object, and tools for working with these arrays. If you are already familiar with MATLAB, you might find this tutorial useful to get started with Numpy. <br>
http://cs231n.github.io/python-numpy-tutorial/

In [ ]:
import numpy as np

a = np.array([1, 2, 3])   # Create a rank 1 array
print(type(a))            # Prints "<class 'numpy.ndarray'>"
print(a.shape)            # Prints "(3,)"
print(a[0], a[1], a[2])   # Prints "1 2 3"
a[0] = 5                  # Change an element of the array
print(a)                  # Prints "[5, 2, 3]"

b = np.array([[1,2,3],[4,5,6]])    # Create a rank 2 array
print(b.shape)                     # Prints "(2, 3)"
print(b[0, 0], b[0, 1], b[1, 0])   # Prints "1 2 4"

Numpy also provides many functions to create arrays:

In [ ]:
a = np.zeros((2,2))   # Create an array of all zeros
print(a)              # Prints "[[ 0.  0.]
                      #          [ 0.  0.]]"

b = np.ones((1,2))    # Create an array of all ones
print(b)              # Prints "[[ 1.  1.]]"

c = np.full((2,2), 7)  # Create a constant array
print(c)               # Prints "[[ 7.  7.]
                       #          [ 7.  7.]]"

d = np.eye(2)         # Create a 2x2 identity matrix
print(d)              # Prints "[[ 1.  0.]
                      #          [ 0.  1.]]"

e = np.random.random((2,2))  # Create an array filled with random values
print(e)                     # Might print "[[ 0.91940167  0.08143941]
                             #               [ 0.68744134  0.87236687]]"

### Array indexing ###
Numpy offers several ways to index into arrays.

Slicing: Similar to Python lists, numpy arrays can be sliced.
Since arrays may be multidimensional, you must specify
a slice for each dimension of the array:

In [ ]:
import numpy as np

# Create the following rank 2 array with shape (3, 4)
# [[ 1  2  3  4]
#  [ 5  6  7  8]
#  [ 9 10 11 12]]
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

# Use slicing to pull out the subarray consisting of the first 2 rows
# and columns 1 and 2; b is the following array of shape (2, 2):
# [[2 3]
#  [6 7]]
b = a[:2, 1:3]

# A slice of an array is a view into the same data, so modifying it
# will modify the original array.
print(a[0, 1])   # Prints "2"
b[0, 0] = 77     # b[0, 0] is the same piece of data as a[0, 1]
print(a[0, 1])   # Prints "77"

In [ ]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
b = a[:2, 1:3]
print(b)

You can also mix integer indexing with slice indexing. However, doing so will yield an array of lower rank than the original array. Note that this is quite different from the way that MATLAB handles array slicing:

In [ ]:
import numpy as np

# Create the following rank 2 array with shape (3, 4)
# [[ 1  2  3  4]
#  [ 5  6  7  8]
#  [ 9 10 11 12]]
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

# Two ways of accessing the data in the middle row of the array.
# Mixing integer indexing with slices yields an array of lower rank,
# while using only slices yields an array of the same rank as the
# original array:
row_r1 = a[1, :]    # Rank 1 view of the second row of a
row_r2 = a[1:2, :]  # Rank 2 view of the second row of a
print(row_r1, row_r1.shape)  # Prints "[5 6 7 8] (4,)"
print(row_r2, row_r2.shape)  # Prints "[[5 6 7 8]] (1, 4)"

# We can make the same distinction when accessing columns of an array:
col_r1 = a[:, 1]
col_r2 = a[:, 1:2]
print(col_r1, col_r1.shape)  # Prints "[ 2  6 10] (3,)"
print(col_r2, col_r2.shape)  # Prints "[[ 2]
                             #          [ 6]
                             #          [10]] (3, 1)"

**Integer array indexing**: When you index into numpy arrays using slicing, the resulting array view will always be a subarray of the original array. In contrast, integer array indexing allows you to construct arbitrary arrays using the data from another array. Here is an example:

In [ ]:
a = np.array([[1,2], [3, 4], [5, 6]])

# An example of integer array indexing.
# The returned array will have shape (3,) and
print(a[[0, 1, 2], [0, 1, 0]])  # Prints "[1 4 5]"

# The above example of integer array indexing is equivalent to this:
print(np.array([a[0, 0], a[1, 1], a[2, 0]]))  # Prints "[1 4 5]"

# When using integer array indexing, you can reuse the same
# element from the source array:
print(a[[0, 0], [1, 1]])  # Prints "[2 2]"

# Equivalent to the previous integer array indexing example
print(np.array([a[0, 1], a[0, 1]]))  # Prints "[2 2]"

One useful trick with integer array indexing is selecting or mutating one element from each row of a matrix:

In [ ]:
# Create a new array from which we will select elements
a = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])

print(a)  # prints "array([[ 1,  2,  3],
          #                [ 4,  5,  6],
          #                [ 7,  8,  9],
          #                [10, 11, 12]])"

# Create an array of indices
b = np.array([0, 2, 0, 1])

# Select one element from each row of a using the indices in b
print(a[np.arange(4), b])  # Prints "[ 1  6  7 11]"

# Mutate one element from each row of a using the indices in b
a[np.arange(4), b] += 10

print(a)  # prints "array([[11,  2,  3],
          #                [ 4,  5, 16],
          #                [17,  8,  9],
          #                [10, 21, 12]])

In [ ]:
np.arange(4)

**Boolean array indexing**: Boolean array indexing lets you pick out arbitrary elements of an array. Frequently this type of indexing is used to select the elements of an array that satisfy some condition. Here is an example:

In [ ]:
a = np.array([[1,2], [3, 4], [5, 6]])

bool_idx = (a > 2)   # Find the elements of a that are bigger than 2;
                     # this returns a numpy array of Booleans of the same
                     # shape as a, where each slot of bool_idx tells
                     # whether that element of a is > 2.

print(bool_idx)      # Prints "[[False False]
                     #          [ True  True]
                     #          [ True  True]]"

# We use boolean array indexing to construct a rank 1 array
# consisting of the elements of a corresponding to the True values
# of bool_idx
print(a[bool_idx])  # Prints "[3 4 5 6]"

# We can do all of the above in a single concise statement:
print(a[a > 2])     # Prints "[3 4 5 6]"

For brevity we have left out a lot of details about numpy array indexing; if you want to know more you should read the documentation. <br>
https://docs.scipy.org/doc/numpy/reference/arrays.indexing.html

### Datatypes
https://docs.scipy.org/doc/numpy/reference/arrays.dtypes.html

In [ ]:
import numpy as np

x = np.array([1, 2])   # Let numpy choose the datatype
print(x.dtype)         # Prints "int64"

x = np.array([1.0, 2.0])   # Let numpy choose the datatype
print(x.dtype)             # Prints "float64"

x = np.array([1, 2], dtype=np.int64)   # Force a particular datatype
print(x.dtype)                         # Prints "int64"

### Array math
Basic mathematical functions operate elementwise on arrays, and are available both as operator overloads and as functions in the numpy module:

In [ ]:
import numpy as np

x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)

# Elementwise sum; both produce the array
# [[ 6.0  8.0]
#  [10.0 12.0]]
print(x + y)
print(np.add(x, y))

# Elementwise difference; both produce the array
# [[-4.0 -4.0]
#  [-4.0 -4.0]]
print(x - y)
print(np.subtract(x, y))

# Elementwise product; both produce the array
# [[ 5.0 12.0]
#  [21.0 32.0]]
print(x * y)
print(np.multiply(x, y))

# Elementwise division; both produce the array
# [[ 0.2         0.33333333]
#  [ 0.42857143  0.5       ]]
print(x / y)
print(np.divide(x, y))

# Elementwise square root; produces the array
# [[ 1.          1.41421356]
#  [ 1.73205081  2.        ]]
print(np.sqrt(x))

Note that unlike MATLAB, * is elementwise multiplication, not matrix multiplication. We instead use the **dot** function to compute inner products of vectors, to multiply a vector by a matrix, and to multiply matrices. **dot** is available both as a function in the numpy module and as an instance method of array objects:

In [ ]:
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

v = np.array([9,10])
w = np.array([11, 12])

# Inner product of vectors; both produce 219
print(v.dot(w))
print(np.dot(v, w))

# Matrix / vector product; both produce the rank 1 array [29 67]
print(x.dot(v))
print(np.dot(x, v))

# Matrix / matrix product; both produce the rank 2 array
# [[19 22]
#  [43 50]]
print(x.dot(y))
print(np.dot(x, y))

Numpy provides many useful functions for performing computations on arrays; one of the most useful is **sum**. For other functions are :
https://docs.scipy.org/doc/numpy/reference/routines.math.html

In [ ]:
x = np.array([[1,2],[3,4]])

print(np.sum(x))  # Compute sum of all elements; prints "10"
print(np.sum(x, axis=0))  # Compute sum of each column; prints "[4 6]"
print(np.sum(x, axis=1))  # Compute sum of each row; prints "[3 7]"

we frequently need to reshape or otherwise manipulate data in arrays. The simplest example of this type of operation is transposing a matrix; to transpose a matrix, simply use the T attribute of an array object:

In [ ]:
x = np.array([[1,2], [3,4]])
print(x)    # Prints "[[1 2]
            #          [3 4]]"
print(x.T)  # Prints "[[1 3]
            #          [2 4]]"

# Note that taking the transpose of a rank 1 array does nothing:
v = np.array([1,2,3])
print(v)    # Prints "[1 2 3]"
print(v.T)  # Prints "[1 2 3]"

Numpy provides many more functions for manipulating arrays; you can see the full list in the documentation.
https://docs.scipy.org/doc/numpy/reference/routines.array-manipulation.html

### Broadcasting

Broadcasting is a powerful mechanism that allows numpy to work with arrays of different shapes when performing arithmetic operations. Frequently we have a smaller array and a larger array, and we want to use the smaller array multiple times to perform some operation on the larger array.

For example, suppose that we want to add a constant vector to each row of a matrix. We could do it like this:

In [ ]:
import numpy as np

# We will add the vector v to each row of the matrix x,
# storing the result in the matrix y
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
y = np.empty_like(x)   # Create an empty matrix with the same shape as x

# Add the vector v to each row of the matrix x with an explicit loop
for i in range(4):
    y[i, :] = x[i, :] + v

# Now y is the following
# [[ 2  2  4]
#  [ 5  5  7]
#  [ 8  8 10]
#  [11 11 13]]
print(y)

This works; however when the matrix **x** is very large, computing an explicit loop in Python could be slow. Note that adding the vector **v** to each row of the matrix **x** is equivalent to forming a matrix **vv** by stacking multiple copies of **v** vertically, then performing elementwise summation of **x** and **vv**. We could implement this approach like this:

In [ ]:
# We will add the vector v to each row of the matrix x,
# storing the result in the matrix y
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
vv = np.tile(v, (4, 1))   # Stack 4 copies of v on top of each other
print(vv)                 # Prints "[[1 0 1]
                          #          [1 0 1]
                          #          [1 0 1]
                          #          [1 0 1]]"
y = x + vv  # Add x and vv elementwise
print(y)  # Prints "[[ 2  2  4
          #          [ 5  5  7]
          #          [ 8  8 10]
          #          [11 11 13]]"

Numpy broadcasting allows us to perform this computation without actually creating multiple copies of **v**. Consider this version, using broadcasting:

The line **y = x + v** works even though **x** has shape **(4, 3)** and **v** has shape **(3,)** due to broadcasting; this line works as if **v** actually had shape **(4, 3)**, where each row was a copy of **v**, and the sum was performed elementwise.

In [ ]:
# We will add the vector v to each row of the matrix x,
# storing the result in the matrix y
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
y = x + v  # Add v to each row of x using broadcasting
print(y)  # Prints "[[ 2  2  4]
          #          [ 5  5  7]
          #          [ 8  8 10]
          #          [11 11 13]]"

Broadcasting two arrays together follows these rules:

(1) If the arrays do not have the same rank, prepend the shape of the lower rank array with 1s until both shapes have the same length. <br>

(2) The two arrays are said to be compatible in a dimension if they have the same size in the dimension, or if one of the arrays has size 1 in that dimension. <br>

(3) The arrays can be broadcast together if they are compatible in all dimensions. <br>

(4) After broadcasting, each array behaves as if it had shape equal to the elementwise maximum of shapes of the two input arrays. <br>

(5) In any dimension where one array had size 1 and the other array had size greater than 1, the first array behaves as if it were copied along that dimension <br>

If this explanation does not make sense, try reading the explanation from the documentation
https://docs.scipy.org/doc/numpy/user/basics.broadcasting.html

<br>

Functions that support broadcasting are known as universal functions. You can find the list of all universal functions in the documentation.

Here are some applications of broadcasting:

In [ ]:
import numpy as np

# Compute outer product of vectors
v = np.array([1,2,3])  # v has shape (3,)
w = np.array([4,5])    # w has shape (2,)
# To compute an outer product, we first reshape v to be a column
# vector of shape (3, 1); we can then broadcast it against w to yield
# an output of shape (3, 2), which is the outer product of v and w:
# [[ 4  5]
#  [ 8 10]
#  [12 15]]
print(np.reshape(v, (3, 1)) * w)

# Add a vector to each row of a matrix
x = np.array([[1,2,3], [4,5,6]])
# x has shape (2, 3) and v has shape (3,) so they broadcast to (2, 3),
# giving the following matrix:
# [[2 4 6]
#  [5 7 9]]
print(x + v)

# Add a vector to each column of a matrix
# x has shape (2, 3) and w has shape (2,).
# If we transpose x then it has shape (3, 2) and can be broadcast
# against w to yield a result of shape (3, 2); transposing this result
# yields the final result of shape (2, 3) which is the matrix x with
# the vector w added to each column. Gives the following matrix:
# [[ 5  6  7]
#  [ 9 10 11]]
print((x.T + w).T)
# Another solution is to reshape w to be a column vector of shape (2, 1);
# we can then broadcast it directly against x to produce the same
# output.
print(x + np.reshape(w, (2, 1)))

# Multiply a matrix by a constant:
# x has shape (2, 3). Numpy treats scalars as arrays of shape ();
# these can be broadcast together to shape (2, 3), producing the
# following array:
# [[ 2  4  6]
#  [ 8 10 12]]
print(x * 2)

In [ ]:
v = np.array([1,2,3])
print(np.reshape(v, (3, 1)))

# matplotlib

Matplotlib is a comprehensive library for creating static, animated, and interactive visualizations in Python.<br>
Matplotlib는 파이썬에서 자료를 차트(chart)나 플롯(plot)으로 시각화(visulaization)하는 library 이다. <br> Matplotlib는 다음과 같은 정형화된 차트나 플롯 이외에도 저수준 api를 사용한 다양한 시각화 기능을 제공한다.
<br>
라인 플롯(line plot) <br>
스캐터 플롯(scatter plot) <br>
컨투어 플롯(contour plot) <br>
서피스 플롯(surface plot) <br>
바 차트(bar chart) <br>
히스토그램(histogram) <br>
박스 플롯(box plot) <br>
Matplotlib를 사용한 시각화 예제들을 보고 싶다면 Matplotlib 갤러리 웹사이트를 방문한다.<br>
<br>
http://matplotlib.org/gallery.html <br>

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
# Preparing some data for plotting (데이터 준비)
x = np.arange(0, 6, 0.1) # 0에서 6까지 0.1 간격으로 생성
y = np.sin(x)
print(x)

In [ ]:
plt.plot(y)
plt.grid()

In [ ]:
a = [ 1, 'a', 200]  # list
print(a)

In [ ]:
# Plotting a graph (그래프 그리기)
plt.plot(x, y)
plt.show()

plot의 color, linestyle, label 지정하기 <br>
xlabel, ylabel, title, legend 함수 (method)

In [ ]:
# Plotting sine and cosine graphs
x = np.arange(0, 6, 0.1) # 0에서 6까지 0.1 간격으로 생성
y1 = np.sin(x)
y2 = np.cos(x)

plt.plot(x, y1, label="sin")
plt.plot(x, y2, linestyle = "--", label="cos") # cos 함수는 점선으로 그리기
plt.xlabel("x") # x축 이름
plt.ylabel("y") # y축 이름
plt.title('sin & cos')
plt.legend()
plt.show()

### Two Interfaces for the Price of One

In [ ]:
x = np.linspace(0, 10, 100)  # 0에서 10까지 같은 간격으로 100개의 데이터를 생성

In [ ]:
print(x[0:11])

In [ ]:
print(len(x))

In [ ]:
x[0], x[99]

MATLAB-style Interface

In [ ]:
# create the first of two panels and set current axis
plt.subplot(2, 1, 1) # (rows, columns, panel number)
plt.plot(x, np.sin(x))

# create the second panel and set current axis
plt.subplot(2, 1, 2)
plt.plot(x, np.cos(x));

In [ ]:
# create the first of two panels and set current axis
plt.subplot(1, 2, 1) # (rows, columns, panel number)
plt.plot(x, np.sin(x))

# create the second panel and set current axis
plt.subplot(1, 2, 2)
plt.plot(x, np.cos(x));

Object-oriented interface

In [ ]:
# First create a grid of plots
# ax will be an array of two Axes objects
fig, ax = plt.subplots(2)

# Call plot() method on the appropriate object
ax[0].plot(x, np.sin(x))
ax[1].plot(x, np.cos(x));

In [ ]:
# create the first of two panels and set current axis
plt.subplot(2, 1, 1) # (rows, columns, panel number)
plt.plot(x, np.sin(x))
plt.title('sin & cos')
plt.ylabel("y (sin)") # y축 이름
plt.show()

# create the second panel and set current axis
plt.subplot(2, 1, 2)
plt.plot(x, np.cos(x));
plt.xlabel("x") # x축 이름
plt.ylabel("y (cos)") # y축 이름
plt.show()

pyplot.style 이용한 style sheet 지정 및 pyplot.text() 함수를 이용하여 figure 안에 text를 프린트하기
https://matplotlib.org/tutorials/introductory/customizing.html

In [ ]:
from matplotlib import pyplot as plt
print(plt.style.available)

In [ ]:
plt.text(.5, .5, r'$\mu=100,\ \sigma=15$')
plt.show()

In [ ]:
plt.style.use("classic")
plt.text(.5, .5, r'$\mu=100,\ \sigma=15$')
plt.show()

Plotting 4 subplots in a figure:

In [ ]:
from matplotlib import pyplot as plt
for i in range(1, 5):
    plt.subplot(2, 2, i)
    plt.text(0.5, 0.5, str('Subplot %i' % i), ha = 'center')
plt.show()

In [ ]:
# Restart and clear output
import numpy as np
import matplotlib.pyplot as plt
colors = ['red', 'green', 'goldenrod', 'gray']
linestyles = ['-', '--', ':', '-.']
x = np.arange(360, step = 10)
y = np.sin(x*2*np.pi/360)
for i in range(1, 5):
    plt.subplot(2, 2, i)
    plt.plot(x, y, color = colors[i-1], linewidth = i, linestyle = linestyles[i-1])
    plt.grid(True)
plt.show()

In [ ]:
print(x)

스타일 문자열은 색깔(color), 마커(marker), 선 종류(line style)의 순서로 지정한다. 만약 이 중 일부가 생략되면 디폴트값이 적용된다.

In [ ]:
plt.title("style plot such as 'rs--' ")
plt.plot([10, 20, 30, 40], [2, 3, 3, 2], 'rs--')
plt.show()

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
colors = ['red', 'green', 'goldenrod', 'gray']
linestyles = ['-', '--', ':', '-.']
markerstyles = ['^', 'x', 'v', 'o']
x = np.arange(360, step = 20)
y = np.sin(x*2*np.pi/360)
for i in range(1, 5):
    plt.subplot(2, 2, i)
    plt.plot(x, y, marker = markerstyles[i -1], color = colors[i-1], linewidth = 1, linestyle = linestyles[i-1])
    plt.grid(True)
plt.show()

선 투명도 바꾸기 : <br>
선의 투명도도 수정을 할 수가 있는데요. 이건 plot() 함수에서 alpha 속성을 조절하면 되고, 범위는 0.0 (완전 투명, 선이 안 보임. ㅋ) ~ 1.0 (불투명).

In [ ]:
for i in range(1, 5):
    plt.subplot(2, 2, i)
    plt.plot(x, y, alpha = 0.15, color = colors[i-1], linewidth = i, linestyle = linestyles[i-1], marker = markerstyles[i -1])
    plt.grid(True)
plt.show()

선 라벨 표시하기 :
이 그래프 선이 무엇을 보여주는지, 선에 라벨을 붙여주는 기능을 하는 legend().




In [ ]:
for i in range(1, 5):
    plt.subplot(2, 2, i)
    plt.plot(x, y, alpha = 0.35, color = colors[i-1], linewidth = i, linestyle = linestyles[i-1], marker = markerstyles[i -1])
    plt.legend(labels = str(i))
    plt.grid(True)
plt.show()

In [ ]:
for i in range(1, 5):
    plt.subplot(2, 2, i)
    plt.plot(x, y, alpha = 0.75, color = colors[i-1], linewidth = i, linestyle = linestyles[i-1], marker = markerstyles[i -1])
    plt.legend(labels = str(i))
    plt.xlabel('Time')
    plt.ylabel('Amplitude')
    plt.grid(True)
plt.show()

tight_layout() 함수를 추가해주세요. 그럼 겹치는 부분들을
알아서 잘 정리해줍니다.

In [ ]:
for i in range(1, 5):
    plt.subplot(2, 2, i)
    plt.plot(x, y, alpha = 0.75, color = colors[i-1], linewidth = i, linestyle = linestyles[i-1], marker = markerstyles[i -1])
    plt.legend(labels = str(i))
    plt.xlabel('Time')
    plt.ylabel('Amplitude')
    plt.grid(True)
plt.tight_layout()
plt.show()

**축 단위와 범위 지정하기** <br>
각 축 별로 표시되는 값이 항상 정수일 수는 없지요. 그래서 원하는 대로 지정할 수 있도록 xticks(), yticks() 함수를 제공합니다.
xlim(), ylim() 함수를 사용해서, 최소값과 최대값을 각각 입력합니다.


In [ ]:
for i in range(1, 5):
    plt.subplot(2, 2, i)
    plt.plot(x, y, alpha = 0.75, color = colors[i-1], linewidth = i, linestyle = linestyles[i-1], marker = markerstyles[i -1])
    plt.legend(labels = str(i))
    plt.xlabel('Time')
    #plt.ylabel('Amplitude')
    plt.grid(True)
    plt.xticks([0, 100, 200, 300],['0 sec', '1 sec', '2 sec', '3 sec'])
    plt.yticks([-1.0, 0.0, 1.0],['Low', 'Mid', 'High'])
    plt.xlim(-50, 400)
    plt.ylim(-1.5, 1.5)
plt.tight_layout()
plt.show()

화살표를 추가하려면 annotate() 함수를 사용

In [ ]:
for i in range(1, 5):
    plt.subplot(2, 2, i)
    plt.plot(x, y, alpha = 0.75, color = colors[i-1], linewidth = i, linestyle = linestyles[i-1], marker = markerstyles[i -1])
    plt.legend(labels = str(i))
    plt.xlabel('Time')
    plt.annotate('Arrow marking', xy = (200,0), arrowprops={'color':'orange'})
    plt.grid(True)
    plt.xticks([0, 100, 200, 300],['0 sec', '1 sec', '2 sec', '3 sec'])
    plt.yticks([-1.0, 0.0, 1.0],['Low', 'Mid', 'High'])
    plt.xlim(-50, 400)
    plt.ylim(-1.5, 1.5)
plt.tight_layout()
plt.show()

Histogram using pyplot.hist

In [ ]:
import numpy as np
import matplotlib.pyplot as plt

# Fixing random state for reproducibility
np.random.seed(19680801)

mu, sigma = 100, 15
x = mu + sigma * np.random.randn(10000)

# the histogram of the data
n, bins, patches = plt.hist(x, 50, density=True, facecolor='g', alpha=0.75)


plt.xlabel('Smarts')
plt.ylabel('Probability')
plt.title('Histogram of IQ')
plt.text(60, .025, r'$\mu=100,\ \sigma=15$')
plt.xlim(40, 160)
plt.ylim(0, 0.03)
plt.grid(True)
plt.show()

savefig() 함수를 사용하여 그래프를 화일로 저장하기

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
colors = ['red', 'green', 'goldenrod', 'gray']
linestyles = ['-', '--', ':', '-.']
x = np.arange(360, step = 10)
y = np.sin(x*2*np.pi/360)
for i in range(1, 5):
    plt.subplot(2, 2, i)
    plt.plot(x, y, color = colors[i-1], linewidth = i, linestyle = linestyles[i-1])
    plt.grid(True)
fig = plt.gcf()
plt.show()
fig.savefig('plot01.jpg')

### log graph (로그 그래프) <br>

In [ ]:
import matplotlib.pyplot as plt
import numpy as np

te=10
A=0.1
sampling=1000  # Hz
t=np.arange(0, te, 1/sampling)
value= A*t

#plt.figure(num=1,dpi=100,facecolor='white', edgecolor='goldenrod')

In [ ]:
plt.plot(t, value,'r')
plt.title('plot')
plt.xlabel('time($sec$)')
plt.ylabel('value')
plt.grid()
plt.show()

In [ ]:
plt.semilogx(t, value,'r')
plt.title('semilogx')
plt.xlabel('time($sec$)')
plt.ylabel('value')
plt.xticks([0.001,.002,.003,.004,.005,.006,.007,.008,.009, 0.01,.02,.03,.04,.05,.06,.07,.08,.09,
            0.1,.2,.3,.4,.5,.6,.7,.8,.9, 1,2,3,4,5,6,7,8,9,10])

plt.grid()
plt.show()

In [ ]:
plt.semilogy(t, value,'r')
plt.title('semilogy')
plt.xlabel('time($sec$)')
plt.ylabel('value')
plt.yticks([0.001,.002,.003,.004,.005,.006,.007,.008,.009, 0.01,.02,.03,.04,.05,.06,.07,.08,.09,
            0.1,.2,.3,.4,.5,.6,.7,.8,.9, 1,2,3,4,5,6,7,8,9,10])
plt.grid()
plt.show()

In [ ]:
plt.loglog(t, value,'r')
plt.title('loglog')
plt.xlabel('time($sec$)')
plt.ylabel('value')
plt.xticks([0.001,.002,.003,.004,.005,.006,.007,.008,.009, 0.01,.02,.03,.04,.05,.06,.07,.08,.09,
            0.1,.2,.3,.4,.5,.6,.7,.8,.9, 1,2,3,4,5,6,7,8,9,10])
plt.yticks([0.001,.002,.003,.004,.005,.006,.007,.008,.009, 0.01,.02,.03,.04,.05,.06,.07,.08,.09,
            0.1,.2,.3,.4,.5,.6,.7,.8,.9, 1,2,3,4,5,6,7,8,9,10])
plt.grid()
plt.show()

서브 플롯간의 간격을 조절하기 위해서 아래의 subplots_adjust() 함수를 사용하여 레이블간 겹침이 발생하는 문제를 해결

https://techreviewtips.blogspot.com/2017/11/04-06-log.html

In [ ]:
import matplotlib.pyplot as plt
import numpy as np

te=10
A=0.1
sampling=1000  # Hz
t=np.arange(0, te, 1/sampling)
value= A*t

plt.figure(num=1,dpi=100,facecolor='white')
plt.subplots_adjust(hspace = 0.5, wspace = 0.3)

# first suplot .......
plt.subplot(2,2,1)
plt.plot(t, value,'r')
plt.title('plot')
plt.xlabel('time($sec$)')
plt.ylabel('value')
plt.grid()

# second suplot .......
ax=plt.subplot(2,2,2)
plt.semilogx(t, value,'r')
plt.title('semilogx')
plt.xlabel('time($sec$)')
plt.ylabel('value')
plt.xticks([0.001,.002,.003,.004,.005,.006,.007,.008,.009, 0.01,.02,.03,.04,.05,.06,.07,.08,.09,
            0.1,.2,.3,.4,.5,.6,.7,.8,.9, 1,2,3,4,5,6,7,8,9,10])

plt.grid()

# third suplot .......
plt.subplot(2,2,3)
plt.semilogy(t, value,'r')
plt.title('semilogy')
plt.xlabel('time($sec$)')
plt.ylabel('value')
plt.yticks([0.001,.002,.003,.004,.005,.006,.007,.008,.009, 0.01,.02,.03,.04,.05,.06,.07,.08,.09,
            0.1,.2,.3,.4,.5,.6,.7,.8,.9, 1,2,3,4,5,6,7,8,9,10])
plt.grid()

# forth suplot .......
plt.subplot(2,2,4)
plt.loglog(t, value,'r')
plt.title('loglog')
plt.xlabel('time($sec$)')
plt.ylabel('value')
plt.xticks([0.001,.002,.003,.004,.005,.006,.007,.008,.009, 0.01,.02,.03,.04,.05,.06,.07,.08,.09,
            0.1,.2,.3,.4,.5,.6,.7,.8,.9, 1,2,3,4,5,6,7,8,9,10])
plt.yticks([0.001,.002,.003,.004,.005,.006,.007,.008,.009, 0.01,.02,.03,.04,.05,.06,.07,.08,.09,
            0.1,.2,.3,.4,.5,.6,.7,.8,.9, 1,2,3,4,5,6,7,8,9,10])
plt.grid()

#plt.savefig("./test_figure1.png",dpi=300)
plt.show()

### Bar plot

In [ ]:
age = [0, 1, 2, 3, 4, 5]
height = [0.3, 0.6, 0.9, 1.1, 1.2, 1.4]

plt.bar(age,height, color = 'goldenrod')
plt.xlabel('age')
plt.ylabel('height')
plt.title('my first bar plot')
plt.show()

In [ ]:
import numpy as np
import matplotlib.pyplot as plt

# Make a fake grade dataset
height = [12, 18, 28, 22, 18, 11, 1]
bars = ('A+', 'A', 'B+', 'B', 'C+', 'C', 'D+')
y_pos = np.arange(len(bars))

**Uniform color using RGB** <br>
RGB is a way of making colors. You have to to provide <em>color</em><span style="color:magenta">=</span>(<span style="color:red">red</span>, <span style="color:green">green</span> and <span style="color:blue">blue</span> + the <em>transparency</em>) and it returns a color.

In [ ]:
plt.bar(y_pos, height, color=(0.5, 0.4, 0.5, 0.6))
plt.xticks(y_pos, bars)
plt.show()

**Different color for each bar** <br>
If you want to give different colors to each bar, just provide a list of color names to the color argument:

In [ ]:
plt.bar(y_pos, height, color=['purple', 'orange', 'green', 'magenta', 'cyan', 'gray', 'yellow'])
plt.xticks(y_pos, bars)
plt.show()

The **edgecolor** argument allows to color the borders of barplots.

In [ ]:
plt.bar(y_pos, height, color=(0.2, 0.2, 0.2, 0.2),  edgecolor='orange')
plt.xticks(y_pos, bars)
plt.show()


In [ ]:
from matplotlib import pyplot as plt
import numpy as np

plt.style.use("fivethirtyeight")

ages_x = [25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35]

dev_y = [38496, 42000, 46752, 49320, 53200,
         56000, 62316, 64928, 67317, 68748, 73752]
plt.plot(ages_x, dev_y, color="#444444", label="All Devs")

# py_dev_y = [45372, 48876, 53850, 57287, 63016,
#             65998, 70003, 70000, 71496, 75370, 83640]
# plt.plot(ages_x, py_dev_y, color="#008fd5", label="Python")

# js_dev_y = [37810, 43515, 46823, 49293, 53437,
#             56373, 62375, 66674, 68745, 68746, 74583]
# plt.plot(ages_x, js_dev_y, color="#e5ae38", label="JavaScript")

plt.legend()

plt.title("Median Salary (USD) by Age")
plt.xlabel("Ages")
plt.ylabel("Median Salary (USD)")

plt.tight_layout()

plt.show()


In [ ]:
from matplotlib import pyplot as plt
import numpy as np

plt.style.use("fivethirtyeight")

ages_x = [25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35]

dev_y = [38496, 42000, 46752, 49320, 53200,
         56000, 62316, 64928, 67317, 68748, 73752]
plt.plot(ages_x, dev_y, color="#444433", label="All Devs")

py_dev_y = [45372, 48876, 53850, 57287, 63016,
            65998, 70003, 70000, 71496, 75370, 83640]
plt.plot(ages_x, py_dev_y, color="#c65f25", label="Python")

js_dev_y = [37810, 43515, 46823, 49293, 53437,
            56373, 62375, 66674, 68745, 68746, 74583]
plt.plot(ages_x, js_dev_y, color="#e5ce33", label="JavaScript")

plt.legend()

plt.title("Median Salary (USD) by Age")
plt.xlabel("Ages")
plt.ylabel("Median Salary (USD)")

plt.tight_layout()

plt.show()


In [ ]:
import csv
import numpy as np
import pandas as pd
from collections import Counter
from matplotlib import pyplot as plt

plt.style.use("fivethirtyeight")

data = pd.read_csv('data.csv')
ids = data['Responder_id']
lang_responses = data['LanguagesWorkedWith']

language_counter = Counter()

for response in lang_responses:
    language_counter.update(response.split(';'))

languages = []
popularity = []

for item in language_counter.most_common(15):
    languages.append(item[0])
    popularity.append(item[1])

languages.reverse()
popularity.reverse()

plt.barh(languages, popularity, color=['goldenrod'])

plt.title("Most Popular Languages")
# plt.ylabel("Programming Languages")
plt.xlabel("Number of People Who Use")

plt.tight_layout()

plt.show()

### Introducing the N-dimensional array
https://www.pythonlikeyoumeanit.com/Module3_IntroducingNumpy/IntroducingTheNDarray.html

In [ ]:
import numpy as np
x = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
type(x)

In [ ]:
isinstance(x, np.ndarray)

In [ ]:
x

In [ ]:
print(x)

We can “reshape” this array so that its contents can be accessed along 2 dimensions:

In [ ]:
x = x.reshape(3,3)
x

We will utilize one of NumPy’s “vectorized” functions to square each entry in the array (without us needing to write a for-loop)

In [ ]:
np.power(x, 2)

In [ ]:
np.mean(x, axis=0)

In [ ]:
np.mean(x, axis=1)

In [ ]:
x

In [ ]:
x ** np.array([0., 1., 2.])  # [3 by 3]**[1 by 3] becomes [3 by 3]**[3 by 3]

In [ ]:
x ** np.array([[0., 1., 2.], [0., 1., 2.], [0., 1., 2.]])

Basic indexing allows us to access multi-dimensional slices of x:

In [ ]:
import numpy as np
x = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8])
x = x.reshape(3,3)
print(x)

In [ ]:
x[:2, :3]

Advanced indexing can be used to access all even-valued entries of x; let’s update x so that all of its even-valued entries are multiplied by -1:

In [ ]:
x[x % 2 == 0] *= -1
print(x)

In [ ]:
x

### One-dimensional Arrays

In [ ]:
import numpy as np
simple_array = np.array([2.3, 0.1, -9.1]) # A 1-D array, shape-(3,)
np.shape(simple_array)

This array supports the same indexing scheme as Python’s sequences (lists, tuples, and strings):

In [ ]:
#+------+------+------+
#|  2.3 |  0.1 | -9.1 |
#+------+------+------+
#    0      1      2
#   -3     -2     -1

In [ ]:
simple_array[-3]

In [ ]:
simple_array[-1]

In [ ]:
simple_array[1:3]

### Two-dimensional Arrays

In [ ]:
import numpy as np
# A 2-D array, shape-(3, 2)
np.array([[93,  95],
          [84, 100],
          [99,  87]])

In [ ]:
grades = np.array([[93,  95],
                  [84, 100],
                  [99,  87]])
print(grades)

In [ ]:
#            -- axis-1 ->
#              -2  -1
#               0   1
#  |          +---+---+
#  |    -3, 0 |93 | 95|    Ashley
#  |          +---+---+
#axis-0 -2, 1 |84 |100|    Brad
#  |          +---+---+
#  |    -1, 2 |99 | 87|    Cassie
#  V          +---+---+

In [ ]:
grades[1, 0]  # Brad's score on axis-1's 0th item.

In [ ]:
# negative indices work as with lists/tuples/strings
grades[-2, 0]  # Brad's score on Exam 1

Slice Indexing

In [ ]:
grades[0:3, 1]  # Exam 2 scores for all students

In [ ]:
grades[1:, 1]  # equivalent to `grades[1:3, 1]

In [ ]:
grades[:, :1]  # equivalent to `grades[0:3, 0:1]

In [ ]:
grades[:, -1]  # Latest exam scores (Exam 2), for all students

Supplying Fewer Indices Than Dimensions

In [ ]:
grades[0]

### N-dimensional Arrays

In [ ]:
import numpy as np
# A 3-D array, shape-(2, 2, 3)
x = np.array([[[0, 1, 2],
               [2, 3, 4]],

              [[4, 5, 6],
               [6, 7, 8]]])
print(x)

In [ ]:
##   |       -- axis-2 ->
#   |    |
#   |  axis-1 [[[0, 1, 2],
#   |    |      [2, 3, 4]],
#   |    V
#axis-0
#   |      -- axis-2 ->
#   |    |
#   |  axis-1  [[4, 5, 6],
#   |    |      [6, 7, 8]]]
#   V    V

In [ ]:
# Accessing Data Along Multiple Dimensions in an Array
# get: sheet-0, both rows, flip order of columns
x[0, :, :-1]

In [ ]:
# a 3D array, shape-(2, 2, 2)
d3_array = np.array([[[0, 1],
                      [2, 3]],

                     [[4, 5],
                      [6, 7]]])
print(d3_array)

In [ ]:
#   |       -- axis-2 ->
#   |    |
#   |  axis-1 [0, 1]
#   |    |    [2, 3]
#   |    V
#axis-0
#   |      -- axis-2 ->
#   |    |
#   |  axis-1 [4, 5]
#   |    |    [6, 7]
#   V    V

In [ ]:
# retrieving a single element from a 3D-array
d3_array[0, 1, 0]

In [ ]:
# retrieving a 1D sub-array from a 3D-array
d3_array[:, 0, 0]

In [ ]:
d3_array[1]

Zero-dimensional Arrays

In [ ]:
# A 0-D array
np.array(8)

In [ ]:
# creating a 0-dimensional array
x = np.array(15.2)

In [ ]:
x[0]

In [ ]:
x.item()

Introducing the reshape Function

In [ ]:
x = np.array([0, 1, 2, 3, 4, 5])

In [ ]:
# reshape a shape-(6,) array into a shape-(2,3) array
x.reshape(2, 3)

In [ ]:
# equivalent to: x = x.reshape(2, 3)
x.shape = (2, 3)

Of course, the size the the initial array must match the size of the to-be reshaped array:

In [ ]:
# an array with 5 numbers are cannot be reshaped
# into a (3, 2) array
np.array([0, 1, 2, 3, 4]).reshape(3, 2)

Multidimensional arrays can be reshaped too:

In [ ]:
# reshaping a multidimensional array
x = np.array([[ 0,  1,  2,  3],
              [ 4,  5,  6,  7],
              [ 8,  9, 10, 11]])

In [ ]:
# reshape from (3, 4) to (2, 3, 2)
x.reshape(2, 3, 2)

### Basic Mathematical Operations Using Arrays

In [ ]:
import numpy as np

x = np.array([[ 0.,  1.,  2.],
              [ 3.,  4.,  5.],
              [ 6.,  7.,  8.]])

In [ ]:
x ** 2

In [ ]:
np.sqrt(x)

In [ ]:
.5 + x[0, :]

In [ ]:
y = np.array([[-4. , -3.5, -3. ],
              [-2.5, -2. , -1.5],
              [-1. , -0.5, -0. ]])

In [ ]:
x + y   #`x + y` will add the corresponding entries

In [ ]:
x * y

In [ ]:
print(x)

In [ ]:
np.sum(x)   # summing over all of the array's entries

In [ ]:
np.sum(x, axis=0) # summing over the rows, within each column

### Vectorized Operations

the term vectorization describes the use of optimized, pre-compiled code written in a low-level language (e.g. C) to perform mathematical operations over a sequence of data.

ND-arrays are homogeneous: an array can only contain data of a single type. For instance, an array can contain 8-bit integers or 32-bit floating point numbers, but not a mix of the two. This is in stark contrast to Python’s lists and tuples, which are entirely unrestricted in the variety of contents they can possess

In [ ]:
import numpy as np

In [ ]:
np.sum(np.arange(10000))  # takes 11 micro sec. on my computer

In [ ]:
# sum an array by explicitly looping over the array in Python
# this takes 822 microseconds on my computer
total = 0
for i in np.arange(10000):
    total = i + total
total

In [ ]:
# multiply 2 with each number in the array
2 * np.array([2, 3, 4])

In [ ]:
# subtract the corresponding entries of the two arrays
np.array([10.2, 3.5, -0.9]) - np.array([8.2, 3.5, 6.5])

In [ ]:
# Take the "dot product" of the two arrays
# "dot product" means: multiply their corresponding entries and sum the result
np.dot(np.array([1, -3, 4]), np.array([2, 0, 1]))

### Unaray Functions f(x)

<img src="np_unary.jpg" alt="Drawing" style="width: 350px;"/>

In [ ]:
import numpy as np
x = np.array([0., 1., 2.])

In [ ]:
np.exp(x)

In [ ]:
x = np.array([[-1, 2], [-3, 4]])
print(x)

In [ ]:
np.square(x)  # equivalent to: `x**2`

In [ ]:
x[:, 0] ** 2  # square column-0 of `x`

### Binary Functions f(x, y)

<img src="np_binary.jpg" alt="Drawing" style="width: 550px;"/>

In [ ]:
import numpy as np
x = np.array([0., 1., 2.])
y = np.array([-1., 1., -2.])

In [ ]:
x + y

You can apply binary NumPy functions to arrays of unlike shapes. For instance, you may want to add a single shape-(2,) array with ten of such arrays, which are stored as a single shape-(10,2) array. This process is known as broadcasting, and will be covered in detail in a later section.

In [ ]:
1 + x

In [ ]:
np.array([1, 1, 1]) + x

In [ ]:
x = np.array([[10,  2],
              [ 3,  5]])

In [ ]:
y = np.array([[ 1,   0],
              [ -4,  -1]])

In [ ]:
np.add(x, y)

In [ ]:
x + y

In [ ]:
x[:, 0] + y[1, :]

In [ ]:
#??
x = np.array([[ 0,  1,  2,  3],
              [ 4,  5,  6,  7],
              [ 8,  9, 10, 11],
              [12, 13, 14, 15]])

In [ ]:
3 * np.array([0., 1., 2.])  # convenient notation for calling `np.multiply(3, x)`

In [ ]:
>>> np.array([1., 2., 3.]) ** 2  # convenient notation for calling `np.power(x, 2)`

In [ ]:
x = np.array([[10,  2],
              [ 3,  5]])
np.maximum(4, x)

In [ ]:
# a 3D array of shape-(2, 2, 8)
y = np.array([[[ 0,  1,  2,  3,  4,  5,  6,  7],
               [ 8,  9, 10, 11, 12, 13, 14, 15]],

              [[16, 17, 18, 19, 20, 21, 22, 23],
               [24, 25, 26, 27, 28, 29, 30, 31]]])
y[0, :, ::2] * -1

<img src="np_seq.png" alt="Drawing" style="width: 550px;"/>

In [ ]:
# demonstrating sequential functions
x = np.array([0., 2., 4.])
np.sum(x)  # can also be invoked as `x.sum()`

In [ ]:
x = np.array([[0, 1],
              [2, 3],
              [4, 5]])

In [ ]:
# `sum`  will treat a multidimensional array
# as if it is a single sequence of numbers, by default
np.sum(x)

In [ ]:
# sum over axis-0, within axis-1
# i.e. sum over the rows, within each column
np.sum(x, axis=0)  # equivalent: x.sum(axis=0)

In [ ]:
# sum over axis-1, within axis-0
# i.e. sum over the columns, within each row
np.sum(x, axis=1)  # equivalent: x.sum(axis=1)

In [ ]:
# negative axis-indices can be used too
np.sum(x, axis=-1)  # equivalent: np.sum(x, axis=1)

In [ ]:
# sum over axis-0 and axis-1
# i.e. sum the array as if it were a 1D sequence (default behavior)
np.sum(x, axis=(0, 1))  # equivalent: x.sum(axis=(0, 1))

Understanding the axis argument with a Multi-Dimensional Array

In [ ]:
import numpy as np
x = np.arange(24).reshape(4,2,3)
x

In [ ]:
x[:, 0, 0]

In [ ]:
np.mean(x[:, 0, 0])

In [ ]:
np.mean(x, axis=0)

x[:, 0, :] -> array([ 0,  1,  2,  6,  7,  8, 12, 13, 14, 18, 19, 20])  {mean = 10} <br>
x[:, 1, :] -> array([ 3,  4,  5,  9, 10, 11, 15, 16, 17, 21, 22, 23])  {mean = 13}

In [ ]:
np.mean(x, axis=(0, 2))

Logical Operations

In [ ]:
# check which entries of `x` are less than 6
x = np.array([[ 0,  1,  2,  3],
              [ 4,  5,  6,  7],
              [ 8,  9, 10, 11],
              [12, 13, 14, 15]])

In [ ]:
# returns a boolean-type array
x < 6  # equivalent to `np.less(x, 6)`

In [ ]:
# performing a logical comparison between two arrays
np.array([1, 5, 10]) <=  np.array([1, 5, -1])

The function **allclose** can be used to verify that all corresponding pairs of entries between two arrays are approximately equal in value:

In [ ]:
# checking if two arrays match, using `np.allclose`
x = np.array([0.1, 0.2, 0.3])
y = np.array([1., 2., 3.]) / 10

np.allclose(x, y)

### Image operations
(Textbook 1.6.3) Displaying an image: pyplot에는 이미지를 표시해주는 메서드 (method) imshow()가 있습니다.
이미지를 읽어들일 때는 matplotlib.image 모듈의 imread() 메서드를 이용하고
이미지를 화일로 저장할 때는 imsave() 메서드를 이용합니다.

In [ ]:
import matplotlib.pyplot as plt
from matplotlib.image import imread, imsave
import numpy as np

img = imread('fruit.jpg') # Reading an image
plt.imshow(img)
plt.show()

In [ ]:
# Read an JPEG image into a numpy array
img = imread('fruit.jpg')
print(img.dtype, img.shape)  # Prints "uint8 (321, 377, 3)"

The total sum of all the values in the array. <br>
The colors are ordered red-blue-green along axis-2.

In [ ]:
a = np.array([ 1, 2, 3, 4])
a.sum()

In [ ]:
img.sum()

The minimum blue value in this image.

In [ ]:
min_blue = img[:, :, 2].min(axis=(0, 1))
min_blue

In [ ]:
for i in range(3):  # i=0 : red, i=1 : green, i=2 : blue
    mean = img[:, :, i].mean(axis=(0, 1))
    print(mean)

The mean and standard deviation among all the RGB values in  the image.

In [ ]:
pixel_mean_dev = img.mean(axis=(0,1))
pixel_mean_dev

In [ ]:
pixel_std_dev = img.std(axis=(0,1))
pixel_std_dev

### Array broadcasting of this picture

In [ ]:
print(img.dtype, img.shape)

In [ ]:
#   |       -- axis-2 ->
#   |    |
#   |  axis-1 [0, 1]
#   |    |    [2, 3]
#   |    V
#axis-0
#   |      -- axis-2 ->
#   |    |
#   |  axis-1 [4, 5]
#   |    |    [6, 7]
#   V    V

In [ ]:
print(img)

dtype (데이터 타입)을 unsigned integer에서 float로 변환.

In [ ]:
img_f = img.astype(np.float32)
print(img_f.dtype, img_f.shape)  # Prints "float32 (321, 377, 3)"

In [ ]:
temp = img_f[0:5, 0:2, 0:3]
print(temp.dtype, temp.shape)
print(temp)

Broadcasting of an array

In [ ]:
# We can tint the image by scaling each of the color channels
# by a different scalar constant. The image has shape (321, 377, 3);
# we multiply it by the array [0.6, 0.95, 0.9] of shape (3,);
# numpy broadcasting means that this leaves the red channel unchanged,
# and multiplies the green and blue channels by 0.95 and 0.9
# respectively.
img_tinted = img_f * [0.6, 0.95, 0.9]

In [ ]:
print(img_tinted.dtype, img_tinted.shape)
print(img_tinted[0:5, 0:2, 0:3])

dtype (데이터 타입)을 float에서 다시 unsigned integer로 변환.

In [ ]:
img_u = img_tinted.astype(np.uint8)

In [ ]:
print(img_u.dtype, img_u.shape)
print(img_u[0:5, 0:2, 0:3])

In [ ]:
plt.imshow(img_u)
plt.show()

In [ ]:
pixel_mean_dev = img.mean(axis=(0,1))
pixel_mean_dev

In [ ]:
pixel_mean_dev = img_u.mean(axis=(0,1))
pixel_mean_dev

Reading Comprehension: Basic Sequential Functions

In [ ]:
import matplotlib.pyplot as plt
from matplotlib.image import imread, imsave
import numpy as np

In [ ]:
images = np.random.rand(100, 32, 32, 3)

# Perceptron (퍼셉트론)

In [ ]:
import numpy as np

def AND(x1, x2):
    x = np.array([x1, x2])
    w = np.array([0.5, 0.5])
    tmp = np.sum(w*x)
    if tmp <= 0.7:
        return 0
    else:
        return 1

In [ ]:
print(AND(0,0))
print(AND(1,0))
print(AND(0,1))
print(AND(1,1))

In [ ]:
import numpy as np

def AND(x1, x2):
    x = np.array([x1, x2])
    w = np.array([1.0, 1.0])
    tmp = np.sum(w*x)
    if tmp <= 1.0:
        return 0
    else:
        return 1

In [ ]:
print(AND(0,0))
print(AND(1,0))
print(AND(0,1))
print(AND(1,1))

In [ ]:
import numpy as np

def NAND(x1, x2):
    x = np.array([x1, x2])
    w = np.array([-0.6, -0.5])
    tmp = np.sum(w*x)
    if tmp <= -0.7:
        return 0
    else:
        return 1

In [ ]:
print(NAND(0,0))
print(NAND(1,0))
print(NAND(0,1))
print(NAND(1,1))

In [ ]:
def OR(x1, x2):
    x = np.array([x1, x2])
    w = np.array([0.5, 0.5])
    b = -0.2
    tmp = np.sum(w*x) + b
    if tmp <= 0:
        return 0
    else:
        return 1

In [ ]:
print(OR(0,0))
print(OR(1,0))
print(OR(0,1))
print(OR(1,1))

In [ ]:
import numpy as np

def AND(x1, x2):
    x = np.array([x1, x2])
    w = np.array([0.5, 0.5])
    b = -0.7
    tmp = np.sum(w*x) + b
    if tmp <= 0:
        return 0
    else:
        return 1

In [ ]:
print(AND(0,0))
print(AND(1,0))
print(AND(0,1))
print(AND(1,1))

In [ ]:
def XOR(x1, x2):
    s1 = NAND(x1, x2)
    s2 = OR(x1, x2)
    y = AND(s1, s2)
    return y

In [ ]:
print(XOR(0,0))
print(XOR(1,0))
print(XOR(0,1))
print(XOR(1,1))

In [ ]:
# coding: utf-8
import numpy as np
import matplotlib.pylab as plt

In [ ]:
def step_function(x):
    if x > 0:
        return 1
    else:
        return 0

In [ ]:
step_function(3.0)

In [ ]:
step_function(3)

In [ ]:
step_function(np.array[1.0, 2.0])

In [ ]:
np.array[1.0, 2.0]

In [ ]:
np.array([1.0, 2.0])

In [ ]:
def step_function(x):
    y = x > 0
    return y.astype(np.int)

In [ ]:
step_function(np.array([-1.0, 2.0]))

In [ ]:
x = np.array([-1.0, 1.0, 2.0])
x

In [ ]:
y = x > 0
y

In [ ]:
y = y.astype(np.int)
y

In [ ]:
def step_function(x):
    return np.array(x > 0, dtype=np.int)

In [ ]:
X = np.arange(-5.0, 5.0, 0.1)
Y = step_function(X)

In [ ]:
plt.plot(X, Y)

In [ ]:
for i in range(5):
    print(i)